# Generated by Django 3.0.7 on 2020-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='about',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
