# Generated by Django 3.0.7 on 2020-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200620_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pic/'),
        ),
    ]
